title: Postdocs Lunch Seminar
description: >-
    This is website of the UCSD postdocs' seminar. The main idea of the seminar is
    to help postdocs to know everyone's research topics. On every meeting someone
    gives an approachable talk into her/his research or a question he/she is
    currently thinking about. The seminar promotes a vibrant atmosphere in an
    informal setting.

baseurl: "/Agora"
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
sass:
    sass_dir: _sass

collections:
    talks:
        output: true

permalink: /:categories/:year/:month/:day/:title:output_ext
future: true

defaults:
  -
    scope:
      path: "_talks"
    values:
      layout: "talk"
